### ISSUE TITLE
Incompatible with system DSA5

### ISSUE THREAD

**Issue by Danii0206** [League-of-Foundry-Developers/Chat-Commands-Lib#4]
Hi,
this module makes all chat messages appear twice when used in a game with the system dsa5. I messaged the system developers and they said it is probably because you and them overwrite the same chat-function. Is this fixable on your side?
Kind regards
Danii

**Comment by cswendrowski** [comment]
Hey there @Danii0206 - I took a look into this, and unfortunately the DSA5 devs are going to have to fix this on their end. I recommend they use the `createChatMessage` hook instead of the `chatMessageHook` - I'm not sure why they would be using the same hook as this library just for normal chat messages
