### ISSUE TITLE
Compatibility Issue: Autocomplete Whisper

### ISSUE THREAD

**Issue by shinkei13** [League-of-Foundry-Developers/Chat-Commands-Lib#5]
It appears that this module and [Autocomplete Whisper](https://github.com/orcnog/autocomplete-whisper/) both utilize the same method to register "keydown.menufocus". It appears that because of that, you cannot use both modules without breaking the keyboard functionality of Autocomplete Whisper.

Chat Commands Autocomplete still retains keyboard functionality however.

I've already posted this [there](https://github.com/orcnog/autocomplete-whisper/issues/38), however since this is the newer of the two modules, I figured it couldn't hurt to alert you.

**Comment by brother-oak** [comment]
Not sure if this mod is active, and this problem is an issue for me too.
I have got a workaround that works for me, but YMMV, especially as this module is a library for other modules, so this workaround may break other functionality.
For context, I only use this module as a dependency for DF Chat Enhancements (as I use the adventure logging functionality in there) but I also use Autocomplete whisper. I don't use any other modules that depend on this one.

My workaround must (obviously) be made locally, and make sure you don't update this module, or you will overwrite the change.

You need to create your own version of this mod, and edit the file
Autocomplete.mjs
and comment out the following lines (line #17 and #18):
//        $("#chat-message").off("keydown");
//        $("#chat-message").on("keydown.menufocus", jumpToMenuHandler);

This will prevent the up/down keys from being bound to this module, allowing them to work in autocomplete whisper.

It does mean that you cannot move up and down and select from the menu that this module displays, listing the available chat commands based on your chat input so far. The menu is still displayed, but it is not selectable via arrow keys (you can still select via mouse). I don't think this is a major issue, as I doubt many people will select from this menu via keyboard.

**Comment by cswendrowski** [comment]
Resolved as of 1.4.0
