### ISSUE TITLE
Incompatibility with Dice Tray mod

### ISSUE THREAD

**Issue by GambetTV** [League-of-Foundry-Developers/Chat-Commands-Lib#9]
For some reason this module causes the Dice Tray module to go completely white, making it very hard to read.

**Comment by AaronLip** [comment]
I believe [these lines cause the problem](https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib/blob/8eb34ef22c0d6479b639373c8ec768d3fb5cb5d1/scripts/Autocomplete.mjs#L7-L14) seen below:
![The HTML object that duplicates the text box](https://i.imgur.com/AuGP46y.png)

It can be fixed by setting `display: none;` in the [stylesheet](https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib/blob/bd8f60b287ce34c30f6f9c30320334f43ab0df38/styles/chatcommands.css) and doesn't seem to stop the autocomplete functionality.

**Comment by anthonyronda** [comment]
@GambetTV can you confirm 1.3.3 fixes this for you? If so feel free to close
